authentik:
  secret_key: "tata"
  error_reporting:
    enabled: false
  postgresql:
    host: "host"
    port: 5432
    name: "name"
    user: "user"
    password: "pwdpsql"
geoip:
  enabled: false
ingress:
  enabled: false
postgresql:
  enabled: false
redis:
  enabled: true
image:
  repository: ghcr.io/goauthentik/server
  tag: 2022.3.2
